# Generated by Django 4.0.1 on 2022-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان مقاله'),
        ),
    ]
